{% set name = "fABBA" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 54c9688411fae4e1564e74b52890aff85afd0bc39f5b214da67a522de5ff0f1a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - pandas
    - requests
    - matplotlib-base
    - scikit-learn
    - scipy >=1.2.1

test:
  imports:
    - fABBA
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/nla-group/fABBA
  summary: An efficient aggregation method for the symbolic representation of temporal data.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/nla-group/fABBA

extra:
  recipe-maintainers:
    - guettel
    - chenxinye
