{% set name = "fABBA" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: af95e6beab98a71e96bc8261d12e18029ae3a5b3c0aa3acb39ed02bdbf78c7d3

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  host:
    - python
    - pip
    - setuptools
    - wheel
    - numpy
    - cython

  run:
    - python
    - numpy
    - scipy >=1.2.1
    - pandas
    - requests
    - matplotlib-base
    - scikit-learn

test:
  imports:
    - fABBA
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/nla-group/fABBA
  summary: An efficient aggregation method for the symbolic representation of temporal data.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/nla-group/fABBA

extra:
  recipe-maintainers:
    - guettel
    - chenxinye
